name: Unit test

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container: kalmaradam/test:latest
    steps:
      - uses: actions/checkout@v2
      - name: Gtest CMake
        run: cd /usr/src/gtest && cmake CMakeLists.txt && make
      - name: Symbolic links
        run: ln -st /usr/lib/ /usr/src/gtest/libgtest.a && ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
      - name: CMake test
        run: cmake test/CMakeLists.txt
      - name: Build tests
        run: cd test && make
      - name: Run tests
        run: cd test && ./runTests