name: Unit Test workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: kalmaradam/test:latest
    steps:
      - name: Gtest
        run: cd /usr/src/gtest && cmake . && make && cp *.a /usr/lib && ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
        
      - uses: actions/checkout@v2

      - name: Build
        run: make unittest-build
      - name: Run test
        run: make unittest-run