name: Unit test

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container: mesmatyas/mosze_main:latest
    steps:
      - uses: actions/checkout@v2
      - name: Make build environment
        run: cd /usr/src/gtest && cmake CMakeLists.txt && make
      - name: change permissions
        run:  chmod +x test/parser_test.cpp
      - name: Make references
        run: ln -st /usr/lib/ /usr/src/gtest/libgtest.a && ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
      - name: Make build environment for the test
        run: cmake test/CMakeLists.txt
      - name: Build the test
        run: cd test && make
      - name: Run the unit tests
        run: cd test && ./runTests